Teste do método classIdentifier() - Sprint Julio
devpass-tech/challenge-tests-finance pull request #39
Opened 2022-04-20 12:51 UTC by TatianaRico

### Descrição simples da nova feature
 adicionado teste do metodo classIdentifier()

### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [X] Não adiciona código duplicado
- [X] Não contém código comentado
- [X] Não contém código WIP

2022-04-20 17:58 UTC, jjfernandes87 requested changes

2022-04-20 17:58 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-2/FinanceAppTests/UITableViewCellTests.swift
> +final class UITableViewCellTests: XCTestCase {
Uma sugestão de mudança
**de**
`let sut = ActivityCellView.classIdentifier()`
**para** 
`var sut: UITableViewCell = ActivityCellView.classIdentifier()`

E depois para fazer a segunda validação vc atribui um novo valor para o seu sut sendo o ContactCellView

2022-04-20 18:09 UTC, TatianaRico commented on solutions/devsprint-julio-fernandes-2/FinanceAppTests/UITableViewCellTests.swift
> +final class UITableViewCellTests: XCTestCase {
o tipo do sut é uma string, pq o método classIdentifier retorna uma string

2022-04-25 11:40 UTC, jjfernandes87 approved these changes

2022-04-25 11:40 UTC, merged