feat: add unitary tests to formattedAgency method
devpass-tech/challenge-tests-finance pull request #40
Opened 2022-04-20 20:31 UTC by phmb2

------------ APAGAR ------------
Emojis para os titulos dos MR's
* ✨ - Introduce new features
* 🚧 - Work in progress
More on: https://gitmoji.dev
------------ APAGAR ------------
 
### Descrição simples da nova feature
 
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP
 
### Evidências da feature:
<img width="765" alt="formattedAgencyTests" src="https://user-images.githubusercontent.com/12787225/164310713-c4c2dca4-8bbc-4f80-9f35-9901aaae9aef.png">

2022-04-20 20:38 UTC, Brun41v35 commented on solutions/devsprint-julio-fernandes-2/FinanceAppTests/UserProfileTests.swift
> +    var sut: UserProfile?
[Question]
Fala @pedromartinsbarbosa, uma dúvida, é necessário deixar esse optional ? Acredito que na linha 17 ele recebe um valor. O compilador reclama ?

2022-04-24 12:35 UTC, phmb2 commented on solutions/devsprint-julio-fernandes-2/FinanceAppTests/UserProfileTests.swift
> +    var sut: UserProfile?
@Brun41v35, sim. Como visto na aula, para liberar memória é necessário tornar sut uma variável opcional e também criar e resetar esta propriedade utilizando as funções de configuração (setUp, setUpWithError) e desconfiguração (tearDown, tearDownWithError).

2022-04-25 11:43 UTC, jjfernandes87 requested changes

2022-04-25 11:43 UTC, jjfernandes87 commented on solutions/devsprint-julio-fernandes-2/FinanceAppTests/UserProfileTests.swift
> +        if let value = sut {
A forma como você tratou o sut criando um if let não esta errado, porem não temos o retorno se ele for nulo. 

O que acha então de fazer assim? 

let sut = try XCTUnwrap(sut) 

E no metodo você adiciona um throws

2022-04-25 20:45 UTC, merged