fechActivityDetailsTests
devpass-tech/challenge-tests-finance pull request #59
Opened 2022-05-10 23:22 UTC by matheusvmg

### Descrição simples da nova feature
Added Tests in FinanceService Class, tested if fetchActivityDetailsMethod is returning the correct information, created the mock for network client and injected via dependency, created the activity_details_enpoint.json for retrieve the mocked data,
added tests when an error occur and validate if we can get the right resource name.
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP

2022-05-11 00:58 UTC, Brun41v35 commented on solutions/devsprint-attekita-3/FinanceAppTests/Mocks/NetworkClientMock.swift
> +class NetworkClientMock: NetworkClientProtocol {
opa @matheusvmg, o que acha de colocar a palavra "final" antes da class ?
O "**final**" basicamente não deixa que a classe "NetworkClienteMock" seja herdada por outra e o mais importante ajuda no tempo de compilação.

2022-05-11 00:58 UTC, Brun41v35 commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +class FinanceServiceTests: XCTestCase {
Acho que aqui também seria interessante a palavra "**final**".

2022-05-11 00:58 UTC, Brun41v35 commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +        let expectations = self.expectation(description: "WhenJSONDecoded_ShouldBeNotNil")
opa @matheusvmg, uma dúvida.. O que seria esse **expectations** ?

2022-05-11 00:58 UTC, Brun41v35 commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +                expectations.fulfill()
Outra dúvida hahaha
O que seria esse **fulfill** ?

2022-05-11 00:58 UTC, Brun41v35 commented on solutions/devsprint-attekita-3/Podfile.lock
> +  - SnapshotTesting (1.9.0)
opa @matheusvmg, poderia remover o arquivo .lock ?

2022-05-11 02:01 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Mocks/NetworkClientMock.swift
> +class NetworkClientMock: NetworkClientProtocol {
Sim, ótimo msm..eu tinha esquecido

2022-05-11 02:04 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +class FinanceServiceTests: XCTestCase {
Realmente faz muito sentido.

2022-05-11 02:12 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +                expectations.fulfill()
respondi ali em cima hehe

2022-05-11 02:12 UTC, matheusvmg commented on solutions/devsprint-attekita-3/Podfile.lock
> +  - SnapshotTesting (1.9.0)
claro sem problemas

2022-05-11 13:35 UTC, Bullas commented on solutions/devsprint-attekita-3/FinanceAppTests/Mocks/NetworkClientMock.swift
> +class NetworkClientMock: NetworkClientProtocol {
Boa @Brun41v35  :)

2022-05-11 14:20 UTC, Bullas requested changes

2022-05-11 14:40 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +class FinanceServiceTests: XCTestCase {
Ah simm, entendi..legal, vou alterar simm, era mais curiosidade se tinha tanta diferença quando era nos testes.

2022-05-11 14:52 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceApp.xcodeproj/xcshareddata/xcschemes/FinanceApp.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
vish, agora que percebi hehe, vou retirar!!

2022-05-11 14:57 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Mocks/NetworkClientMock.swift
> +    func getResourceName(url: URL) -> String {
Eu ia deixar como private mas como terminei escrevendo um testes para verificar se ela estava se comportando da maneira esperada terminei deixando como pública, mas posso retirar o teste e deixa-la como private, sem problemas. Já em relação ao algoritmo que pega o nome do resource, fiz dessa forma pois não tinha conhecimento sobre outra, irei atualizar.

2022-05-11 14:58 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +        sut = nil
Bom ponto, terminei não me atentando quanto a isso.

2022-05-11 14:59 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +    var sut: FinanceService!
simm, irei atualizar.

2022-05-11 18:41 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +            XCTAssertNotNil(result, "the response result fails because it's nil.")
Verdade, não tinha me atentado quanto a isso.

2022-05-11 18:47 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +        let expectations = self.expectation(description: "WhenJSONDecoded_ShouldHaveCorrectInformations")
Legal e realmente ficou muito melhor, achei que ficou mais legível...vou alterar

2022-05-11 18:48 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +    func testFinanceServiceFetchActivityDetailsMethod_WhenJSONDecoded_ResponsePropertiesShouldNotBeEmptyStrings() {
simm, bem interessante mesmo

2022-05-11 18:50 UTC, matheusvmg commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +    func testNetworkClientMock_WhenGivenURLToGetResourceNameMethod_ShouldReturnResourceName() {
Foi retirado, realmente não faz tanto sentido...acho que dei uma viajada nessa hehe

2022-05-11 19:30 UTC, matheusvmg commented
Alterações foram realizadas.

2022-05-11 22:06 UTC, Bullas requested changes

2022-05-11 22:06 UTC, Bullas commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +                expectations.fulfill()
Podemos mudar a estrutura deste teste tambem deixando os asserts para o final?

2022-05-12 12:36 UTC, Bullas commented on solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
> +                expectations.fulfill()
@matheusvmg  apenas esse detalhe acima e ja aprovo seu PR :)

2022-05-12 21:04 UTC, Bullas approved these changes
![](https://media.giphy.com/media/Od0QRnzwRBYmDU3eEO/giphy.gif)

2022-05-12 21:04 UTC, merged