[Attekita] 🚧 Implement test for fetchContactList
devpass-tech/challenge-tests-finance pull request #60
Opened 2022-05-11 20:28 UTC by lysonjeada

### Descrição simples da nova feature
 
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [] Não adiciona código duplicado
- [] Não contém código comentado
- [] Não contém código WIP
 
### Evidências da feature:
| iPhone SE | iPhone 12 Max |
| ------ | ------ |
| print  | print |

2022-05-12 21:09 UTC, lysonjeada commented on solutions/devsprint-attekita-3/FinanceAppTests/ContactListTest.swift
> +        fetchDataCalled = true
@Brun41v35 isso! Por que? Você tem alguma outra sugestão? Obrigada!!

2022-05-12 21:09 UTC, lysonjeada commented on solutions/devsprint-attekita-3/FinanceAppTests/ContactListTest.swift
> +}
@Brun41v35 ótimo! Vou fazer isso

2022-05-12 21:24 UTC, Brun41v35 commented on solutions/devsprint-attekita-3/FinanceAppTests/ContactListTest.swift
> +        fetchDataCalled = true
@lysonjeada Hmmmm, não tenho certeza.. Mas, talvez poderiamos mudar o nome dessa classe para **FinanceServiceProtocolSpy**. O que acha ?
**Spy**: Usamos apenas verificar se algum método ou variavel foi chamado.
**Stub**: É responsavel por validar a lógica/retorno de uma função.

2022-05-16 13:02 UTC, Bullas requested changes

2022-05-16 13:02 UTC, Bullas commented on solutions/devsprint-attekita-3/FinanceAppTests/ContactListTest.swift
> +        let error = HTTPClientError.decodeError
A ideia era criar o erro e passar para o Mock para ele retornar o erro?
Você pode criar uma variável no NetworkCiientMock para setar uma resposta customizada que não seja necessariamente o json padrão que ele busca a partir da url

Poderia ser algo como `var expectedReponse: Result<[Contact], Error>?` e dentro do NetworkClientMock voce checaria se esse variável tem valor e se tivesse retornaria ela mesma como resultado, caso estivesse nulo seguiria para a implementação padrão que ja temos hoje.

2022-05-19 12:33 UTC, Bullas approved these changes
![](https://media.giphy.com/media/U2O50cAkpmTjG/giphy.gif)

2022-05-19 12:34 UTC, merged