✨ ClassIdentifier Method tests
devpass-tech/challenge-tests-finance pull request #61
Opened 2022-05-11 20:59 UTC by matheuslenke

### Descrição simples da nova feature
Criação da classe  UITableViewCellExtensionsTests com os testes para o método classIdentifier, que retorna uma String representando o identificador de uma célula com base no nome de sua classe. Os testes são executados em cima das células customizadas criadas no projeto, e da UITableViewCell padrão
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [] Não adiciona código duplicado
- [] Não contém código comentado
- [] Não contém código WIP

2022-05-11 22:02 UTC, Bullas requested changes

2022-05-11 22:02 UTC, Bullas commented on solutions/devsprint-attekita-3/FinanceAppTests/Extensions/UITableViewCellExtentionsTests.swift
> +        XCTAssertEqual(identifier, "UITableViewCell")
você pode criar pelo menos mais um identificador no mesmo teste com um valor diferente para termos certeza de por exemplo uma resposta macaca `return "UITableViewCell` não passaria?

2022-05-11 22:18 UTC, matheuslenke commented on solutions/devsprint-attekita-3/FinanceAppTests/Extensions/UITableViewCellExtentionsTests.swift
> +        XCTAssertEqual(identifier, "UITableViewCell")
Adicionado! Fiz com a ActivityCellView

2022-05-12 12:31 UTC, Bullas commented on solutions/devsprint-attekita-3/FinanceAppTests/Extensions/UITableViewCellExtentionsTests.swift
> +        XCTAssertEqual(activityCellIdentifier, "ActivityCellView")
```suggestion
        let identifier = UITableViewCell.classIdentifier()
        let activityCellIdentifier = ActivityCellView.classIdentifier()
        
        XCTAssertEqual(identifier, "UITableViewCell")
        XCTAssertEqual(activityCellIdentifier, "ActivityCellView")
```

2022-05-12 12:31 UTC, Bullas commented on solutions/devsprint-attekita-3/FinanceAppTests/Extensions/UITableViewCellExtentionsTests.swift
> +        XCTAssertEqual(activityCellIdentifier, "ActivityCellView")
Muito bom! Apenas um pequeno detalhe para mantermos a estrutura do teste com os asserts no final e o setup no inicio :)

2022-05-12 21:08 UTC, Bullas approved these changes

2022-05-12 22:53 UTC, matheuslenke commented
Resolvi os conflitos, testei localmente e o app e os testes todos rodaram certinho. Só tive que rodar novamente o pod install

2022-05-13 10:19 UTC, merged